// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irqftgfiiuvjcwiifdzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlycWZ0Z2ZpaXV2amN3aWlmZHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzY0OTgsImV4cCI6MjA2NzExMjQ5OH0.sE4vclzfBIPuSgbJQzr7u49jmAVm8JmM2Aghuq4rnWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});